# Generated by rules-clojure pin-deps — do not edit.
DEPS_ARTIFACTS = [
    "org.clojure:clojure:1.12.1",
    "org.clojure:core.specs.alpha:0.4.74",
    "org.clojure:spec.alpha:0.5.238",
]

DEPS_REPOSITORIES = [
    "https://repo1.maven.org/maven2/",
]
