(ns rules-clojure.pin-deps
  "Pin deps.edn Maven coordinates into a rules_jvm_external lock file.

  tools.deps is used only here (resolve + temporary download for shas). Day-to-day
  Bazel fetch should use maven.install + this lock — not tools.deps / ~/.m2."
  (:require [clojure.data.json :as json]
            [clojure.edn :as edn]
            [clojure.java.io :as io]
            [clojure.string :as str]
            [rules-clojure.fs :as fs]
            [rules-clojure.gen-build :as gb]
            [rules-clojure.namespace.find :as find]
            [rules-clojure.namespace.parse :as parse])
  (:import [java.security MessageDigest]
           [java.util.jar JarFile]))

(defn- lib-coord-key
  "org.clojure/clojure + 1.12.1 → org.clojure:clojure (rje artifact key without version)."
  [lib-name]
  (-> (str lib-name)
      (str/replace "/" ":")))

(defn- lib-artifact-string
  "org.clojure/clojure + 1.12.1 → org.clojure:clojure:1.12.1"
  [lib-name version]
  (str (lib-coord-key lib-name) ":" version))

(defn- sha256-file
  [^java.io.File f]
  (let [md (MessageDigest/getInstance "SHA-256")
        buf (byte-array 8192)]
    (with-open [in (io/input-stream f)]
      (loop []
        (let [n (.read in buf)]
          (when (pos? n)
            (.update md buf 0 n)
            (recur)))))
    (str/join (map #(format "%02x" %) (.digest md)))))

(defn- maven-only!
  "Throw if any lib is not a Maven dependency. Git/local may be supported later."
  [basis]
  (doseq [[lib info] (:libs basis)]
    (when-not (:mvn/version info)
      (throw (ex-info
              (str "pin-deps: only Maven (:mvn/version) dependencies are supported "
                   "(git and :local/root may come later). Unsupported: " lib
                   " " (pr-str (select-keys info [:git/url :git/sha :local/root :deps/root])))
              {:lib lib :coord info})))))

(defn- jar-paths-for-lib
  "Classpath jar paths belonging to lib."
  [basis lib]
  (->> (:classpath basis)
       (keep (fn [[path {:keys [lib-name]}]]
               (when (and (= lib-name lib)
                          (re-find #"\.jar$" (str path)))
                 (fs/->path path))))
       vec))

(defn- nses-from-jar-path
  "Clojure namespaces declared in jar (for optional AOT target generation)."
  [jar-path]
  (try
    (with-open [jf (JarFile. (fs/path->file jar-path))]
      (->> (find/sources-in-jar jf find/clj)
           (keep (fn [entry]
                   (when-let [decl (find/read-ns-decl-from-jarfile-entry jf entry find/clj)]
                     (parse/name-from-ns-decl decl))))
           (filter identity)
           distinct
           sort
           vec))
    (catch Exception e
      (binding [*out* *err*]
        (println "pin-deps: warning: could not scan namespaces in" (str jar-path) ":" (.getMessage e)))
      [])))

(defn basis->rje-lock
  "Build a rules_jvm_external v2 lock map from a tools.deps basis.
  Jars must already be on disk under the basis classpath (pin uses tools.deps fetch)."
  [basis]
  (maven-only! basis)
  (let [repos (or (not-empty (mapv :url (vals (:mvn/repos basis))))
                  ["https://repo1.maven.org/maven2/"])
        repo-url (first repos)
        ;; normalize trailing slash
        repo-url (if (str/ends-with? repo-url "/") repo-url (str repo-url "/"))
        artifacts (atom {})
        dependencies (atom {})
        repo-artifacts (atom [])
        aot-manifest (atom {})]
    (doseq [[lib info] (sort-by (comp str key) (:libs basis))]
      (let [version (:mvn/version info)
            coord (lib-coord-key lib)
            jars (jar-paths-for-lib basis lib)
            jar (first jars)]
        (when-not jar
          (throw (ex-info (str "pin-deps: no jar on classpath for " lib) {:lib lib})))
        (let [sha (sha256-file (fs/path->file jar))
              dep-libs (try
                         (or (seq (get (gb/->lib->deps basis) lib)) [])
                         (catch Exception _ []))
              dep-coords (mapv lib-coord-key dep-libs)
              nses (nses-from-jar-path jar)]
          (swap! artifacts assoc coord {:version version
                                        :shasums {:jar sha}})
          (swap! dependencies assoc coord (vec (sort dep-coords)))
          (swap! repo-artifacts conj coord)
          (swap! aot-manifest assoc (str lib)
                 {:coord coord
                  :version version
                  :label (gb/library->label lib)
                  :deps (mapv str dep-libs)
                  :nses (mapv str nses)}))))
    {:lock {:__AUTOGENERATED_FILE_DO_NOT_MODIFY_THIS_FILE_MANUALLY "Generated by rules-clojure pin-deps from deps.edn"
            :version "2"
            :artifacts @artifacts
            :dependencies @dependencies
            :repositories {repo-url (vec (sort @repo-artifacts))}
            :packages {}
            :services {}
            ;; rje validates these when fail_if_repin_required; we disable that for pin-generated locks
            :__INPUT_ARTIFACTS_HASH 0
            :__RESOLVED_ARTIFACTS_HASH 0}
     :aot-manifest @aot-manifest
     :artifacts-list
     (->> @artifacts
          (map (fn [[coord {:keys [version]}]]
                 (str coord ":" version)))
          sort
          vec)}))

(defn write-rje-lock!
  [lock-path lock-map]
  (spit (fs/path->file (fs/->path lock-path))
        (str (json/write-str lock-map {:indent true :escape-slash false})
             "\n")
        :encoding "UTF-8"))

(defn write-artifacts-bzl!
  "Write a Starlark file listing resolved GAV strings for maven.install(artifacts=...)."
  [bzl-path artifacts-list repos]
  (let [content
        (str "# Generated by rules-clojure pin-deps — do not edit.\n"
             "DEPS_ARTIFACTS = [\n"
             (str/join (map #(str "    \"" % "\",\n") artifacts-list))
             "]\n\n"
             "DEPS_REPOSITORIES = [\n"
             (str/join (map #(str "    \"" % "\",\n") repos))
             "]\n")]
    (spit (fs/path->file (fs/->path bzl-path)) content :encoding "UTF-8")))

(defn write-aot-manifest!
  [path manifest]
  (spit (fs/path->file (fs/->path path))
        (str ";; Generated by rules-clojure pin-deps — do not edit.\n"
             (pr-str manifest)
             "\n")
        :encoding "UTF-8"))

(defn pin!
  "Resolve deps.edn with tools.deps, write rje lock + artifacts.bzl + aot manifest."
  [{:keys [deps-edn-path lock-path artifacts-bzl-path aot-manifest-path aliases repository-dir]
    :or {aliases []}}]
  (let [deps-edn-path (fs/absolute (fs/->path deps-edn-path))
        repository-dir (fs/absolute (fs/->path (or repository-dir
                                                   (str (System/getProperty "java.io.tmpdir")
                                                        "/rules-clojure-pin-m2"))))
        _ (fs/ensure-directory repository-dir)
        read-deps (#'gb/read-deps deps-edn-path)
        basis (gb/make-basis {:read-deps read-deps
                              :aliases (mapv keyword aliases)
                              :repository-dir repository-dir
                              :deps-edn-path deps-edn-path})
        {:keys [lock aot-manifest artifacts-list]} (basis->rje-lock basis)
        repos (or (keys (:repositories lock)) ["https://repo1.maven.org/maven2/"])]
    (when lock-path
      (write-rje-lock! lock-path lock)
      (println "wrote" (str lock-path)))
    (when artifacts-bzl-path
      (write-artifacts-bzl! artifacts-bzl-path artifacts-list repos)
      (println "wrote" (str artifacts-bzl-path)))
    (when aot-manifest-path
      (write-aot-manifest! aot-manifest-path aot-manifest)
      (println "wrote" (str aot-manifest-path)))
    {:artifact-count (count artifacts-list)
     :artifacts artifacts-list}))

(defn -main [& args]
  (let [opts (apply hash-map args)
        opts (into {} (map (fn [[k v]] [(edn/read-string k) v]) opts))
        result (pin! opts)]
    (println "pin-deps: pinned" (:artifact-count result) "maven artifacts")
    (shutdown-agents)))
